version: "3.1"
services:

    mysql:
      image: mysql:${MY_SQL_VERSION}
      container_name: mysql
      working_dir: /app
      volumes:
        - ./docker/db_data:/app
        - ./docker/sql/fixtures.sql:/docker-entrypoint-initdb.d/fixtures.sql:ro
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /app
      volumes:
          - .:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${WEBSERVER_PORT}:80"

    php-fpm:
      build: docker/php-fpm
      container_name: php-fpm
      working_dir: /app
      volumes:
        - .:/app
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      environment:
        - DBHOST=mysql
        - DATABASE=app
        - DBUSER=app
        - DBPASSWORD=app
        
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: PhpMyAdmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - MYSQL_USERNAME=app
        - MYSQL_ROOT_PASSWORD=root
      restart: always
      ports:
        - "5050:80"
      depends_on:
        - mysql
